config:
  plugin:
    metrics-by-endpoint: {}
  target: "http://localhost:9090"
  phases: # Se generan 10 usuario virtuales cada segundo por un lapso de 20s
    - duration: 20
      arrivalRate: 10 #Usuarios virtuales
scenarios:
  - name: "Session flow (register + login)"
    flow:
      - log: "Creamos las variables para el user de prueba"
      - get:
          url: "/api/user/test"
          capture:
            - json: "$.first_name"
              as: "first_name"
            - json: "$.last_name"
              as: "last_name"
            - json: "$.email"
              as: "email"
            - json: "$.age"
              as: "age"
            - json: "$.password"
              as: "password"
      - log: "Registrando al usuario:"
      - post:
          url: "/api/session/register"
          json: #Json a modo de request body para esta petición.
            first_name: "{{first_name}}"
            last_name: "{{last_name}}"
            email: "{{email}}"
            age: "{{age}}"
            password: "{{password}}"
      - think: 2 #Simular que el usuario espera 2 segundos para hacer login.
      - log: "Login User"
      - post:
          url: "/api/session/login"
          json: #Json a modo de request body para esta petición.
            email: "{{email}}"
            password: "{{password}}"




